### ISSUE TITLE
Camera doesn't work

### ISSUE THREAD

**Issue by wakedeer** [jarlen/gpuimage-for-android-studio#1]
When i try TAKE PHOTO on my Samsung Galaxy S6 app make ERROR and FINISHED. Why does it happened?
![error2](https://cloud.githubusercontent.com/assets/17357740/14201021/e14c2eae-f7f7-11e5-80dc-d0e5ca4081fa.JPG)

**Comment by jarlen** [comment]
please mark the log

**Comment by wakedeer** [comment]
Helo! Thanks for your help! My camera has resolution 16M (5312 x 2988), maybe is it a problem, because Bitmap is very huge.
These is logcat:
`04-05 09:15:23.021 3690-3737/? W/AASAInstall:  updated apk:jarlen.cn.gpuimage   uid:-1
04-05 09:15:23.031 3690-3713/? I/ActivityManager: Force stopping jarlen.cn.gpuimage appid=10209 user=-1: uninstall pkg
04-05 09:15:23.111 3690-3737/? I/PackageManager: Package jarlen.cn.gpuimage codePath changed from /data/app/jarlen.cn.gpuimage-1 to /data/app/jarlen.cn.gpuimage-2; Retaining data and using new
04-05 09:15:23.111 3690-3737/? I/PackageManager: scanFileNewer : jarlen.cn.gpuimage
04-05 09:15:23.511 3432-3432/? I/dex2oat: /system/bin/dex2oat --zip-fd=11 --zip-location=/data/app/jarlen.cn.gpuimage-2/base.apk --oat-fd=12 --art-fd=-1 --compress-image --oat-location=/data/dalvik-cache/arm/data@app@jarlen.cn.gpuimage-2@base.apk@classes.dex --instruction-set=arm --instruction-set-features=div --runtime-arg -Xms64m --runtime-arg -Xmx512m --swap-fd=13
04-05 09:15:24.611 3690-3737/? W/PackageManager: Code path for pkg : jarlen.cn.gpuimage changing from /data/app/jarlen.cn.gpuimage-1 to /data/app/jarlen.cn.gpuimage-2
04-05 09:15:24.611 3690-3737/? W/PackageManager: Resource path for pkg : jarlen.cn.gpuimage changing from /data/app/jarlen.cn.gpuimage-1 to /data/app/jarlen.cn.gpuimage-2
04-05 09:15:24.611 3690-3713/? I/ActivityManager: Force stopping jarlen.cn.gpuimage appid=10209 user=-1: update pkg
04-05 09:15:24.831 3690-3737/? I/ActivityManager: Force stopping jarlen.cn.gpuimage appid=10209 user=0: pkg removed
04-05 09:15:24.921 4120-4120/? I/MultiWindowAppListInfo: android.intent.action.PACKAGE_REPLACED packageName=jarlen.cn.gpuimage
04-05 09:15:24.971 6902-6902/? I/KLMS-2.5.332:: KLMSAbstractReciever(): onReceive(): Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:jarlen.cn.gpuimage flg=0x4000010 cmp=com.samsung.klmsagent/.listner.MainReciver (has extras) } | timestamp: Tue Apr 05 09:15:24 GMT+03:00 2016
04-05 09:15:24.971 6902-3465/? I/KLMS-2.5.332:: KLMSIntentService(): onHandleIntent().START: Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:jarlen.cn.gpuimage flg=0x4000010 cmp=com.samsung.klmsagent/.service.KLMSIntentService (has extras) }
04-05 09:15:24.991 3690-3690/? W/BackupManagerService: Removing schedule queue dupe of jarlen.cn.gpuimage
04-05 09:15:25.061 3466-3466/? I/PackageControlReceiver: forReplacing=true intent=Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:jarlen.cn.gpuimage flg=0x4000010 cmp=com.samsung.android.app.watchmanager/com.samsung.android.app.twatchmanager.receiver.PackageControlReceiver (has extras) }
04-05 09:15:25.111 3485-3485/? I/com.sec.android.service.health.upgrade.UninstallReceiver: onReceive called  PACKAGE_REMOVED package:jarlen.cn.gpuimage
04-05 09:15:25.171 3690-3712/? I/CrashAnrDetector: onPackageUpdateFinished : jarlen.cn.gpuimage
04-05 09:15:25.601 3690-4568/? I/ActivityManager: Start proc 3660:jarlen.cn.gpuimage/u0a209 for activity jarlen.cn.gpuimage/cn.jarlen.gpuimage.MainActivity
04-05 09:15:25.651 3660-3660/? I/InjectionManager: Constructor jarlen.cn.gpuimage, Feature store :{}
04-05 09:15:25.691 3660-3660/? I/InjectionManager: dispatchOnViewCreated > Target : cn.jarlen.gpuimage.MainActivity isFragment :false
04-05 09:15:26.061 3690-3722/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{3968a1c6 u0 jarlen.cn.gpuimage/cn.jarlen.gpuimage.MainActivity t151} time:44772753
04-05 09:15:26.691 3660-3660/jarlen.cn.gpuimage I/Timeline: Timeline: Activity_launch_request id:jarlen.cn.gpuimage time:44773385
04-05 09:15:26.691 3690-3744/? I/ActivityManager: Skip updateThumbnail for r=ActivityRecord{3968a1c6 u0 jarlen.cn.gpuimage/cn.jarlen.gpuimage.MainActivity t151}
04-05 09:15:26.741 3660-3660/jarlen.cn.gpuimage I/InjectionManager: dispatchOnViewCreated > Target : cn.jarlen.gpuimage.ActivityCamera isFragment :false
04-05 09:15:27.161 3690-3722/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{2b1a392b u0 jarlen.cn.gpuimage/cn.jarlen.gpuimage.ActivityCamera t151} time:44773859
04-05 09:15:27.831 6668-4360/? I/UpdateIcingCorporaServi: Updating corpora: APPS=jarlen.cn.gpuimage, CONTACTS=MAYBE
04-05 09:15:27.931 3485-3485/? I/com.sec.android.service.health.upgrade.UninstallReceiver: onReceive called  PACKAGE_ADDED package:jarlen.cn.gpuimage
04-05 09:15:28.351 4430-4430/? I/DBG_POLICYDM: [com.policydm.XSPPReceiver(52/onReceive)] ACTION_PACKAGE_ADDED. mPkgName:jarlen.cn.gpuimage
04-05 09:15:36.671 3660-5345/? E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                 Process: jarlen.cn.gpuimage, PID: 3660
                                                 java.lang.RuntimeException: An error occured while executing doInBackground()
                                                     at android.os.AsyncTask$3.done(AsyncTask.java:304)
                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                     at java.lang.Thread.run(Thread.java:818)
                                                  Caused by: java.lang.OutOfMemoryError: Failed to allocate a 63489036 byte allocation with 16777216 free bytes and 31MB until OOM
                                                     at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                     at android.graphics.Bitmap.nativeCreate(Native Method)
                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:942)
                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:913)
                                                     at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
                                                     at cn.jarlen.gpuimagelibrary.PixelBuffer.convertToBitmap(PixelBuffer.java:206)
                                                     at cn.jarlen.gpuimagelibrary.PixelBuffer.getBitmap(PixelBuffer.java:123)
                                                     at cn.jarlen.gpuimagelibrary.GPUImage.getBitmapWithFilterApplied(GPUImage.java:291)
                                                     at cn.jarlen.gpuimagelibrary.GPUImage$SaveTask.doInBackground(GPUImage.java:431)
                                                     at cn.jarlen.gpuimagelibrary.GPUImage$SaveTask.doInBackground(GPUImage.java:411)
                                                     at android.os.AsyncTask$2.call(AsyncTask.java:292)
                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                     at java.lang.Thread.run(Thread.java:818) 
04-05 09:15:36.671 3690-4150/? W/ActivityManager:   Force finishing activity 1 jarlen.cn.gpuimage/cn.jarlen.gpuimage.ActivityCamera
04-05 09:15:36.681 3690-4150/? I/ActivityManager: Skip updateThumbnail for r=ActivityRecord{2b1a392b u0 jarlen.cn.gpuimage/cn.jarlen.gpuimage.ActivityCamera t151 f}
04-05 09:15:37.161 3690-3722/? I/Timeline: Timeline: Activity_windows_visible id: ActivityRecord{3968a1c6 u0 jarlen.cn.gpuimage/cn.jarlen.gpuimage.MainActivity t151} time:44783857`

Best Regards

**Comment by jarlen** [comment]
maybe it is from the log ,you can try to compress the bitmap

**Comment by jarlen** [comment]
maybe it is from the log ,you can try to compress the bitmap

**Comment by jarlen** [comment]
maybe it is from the log ,you can try to compress the bitmap
